---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-example-bucket-123
      VersioningConfiguration:
        Status: Enabled
